name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
  release:
    types: [created]
    paths-ignore:
      - "README.md"

jobs:
  # ensure the code builds...
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.1.0

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          make build

  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "0.13.6"
          - "0.14.11"
          - "0.15.5"
          - "1.3.2"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.1.0

      - name: Get dependencies
        run: |
          make deps

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        run: |
          make testacc
